// B2B Engineering Services - Products Database
// Categorized into 5 main professional groups: tools, electrical-ict, building-materials, industrial-equipment, safety-equipment

const productsDB = [
    // TOOLS & HARDWARE (30 Products)
    { id: 1, name: "Professional Hand Tool Set", category: "tools", subcategory: "Hand Tools", description: "Complete professional-grade 150-piece set including wrenches, pliers, and screwdrivers", image: "https://images.unsplash.com/photo-1581244276891-998011506634?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 2, name: "Cordless Power Drill Kit", category: "tools", subcategory: "Power Tools", description: "18V heavy-duty cordless drill with 2 batteries and fast charger", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 3, name: "9-Inch Angle Grinder", category: "tools", subcategory: "Power Tools", description: "High-power industrial angle grinder for metal and concrete cutting", image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 4, name: "Digital Multimeter Pro", category: "tools", subcategory: "Testing", description: "True-RMS digital multimeter for precise electrical diagnostics", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 5, name: "Pneumatic Impact Wrench", category: "tools", subcategory: "Air Tools", description: "High-torque air impact wrench for industrial automotive assembly", image: "https://images.unsplash.com/photo-1586864387789-628af9fea93f?w=500&q=80", industries: ["automotive", "manufacturing"] },
    { id: 6, name: "Laser Level 360", category: "tools", subcategory: "Measuring", description: "Self-leveling green cross-line laser level for construction", image: "https://images.unsplash.com/photo-1534398079543-7ae6d016b86a?w=500&q=80", industries: ["construction"] },
    { id: 7, name: "Adjustable Pipe Wrench", category: "tools", subcategory: "Hand Tools", description: "Heavy-duty 24-inch cast iron pipe wrench for plumbing", image: "https://images.unsplash.com/photo-1581093196277-9f608adec699?w=500&q=80", industries: ["construction"] },
    { id: 8, name: "Professional Bench Vise", category: "tools", subcategory: "Hardware", description: "6-inch heavy-duty table vise with swivel base", image: "https://images.unsplash.com/photo-1581244276891-998011506634?w=500&q=80", industries: ["manufacturing"] },
    { id: 9, name: "Hydraulic Bolt Cutter", category: "tools", subcategory: "Hand Tools", description: "Industrial hydraulic bolt cutter for reinforced steel bars", image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=500&q=80", industries: ["construction"] },
    { id: 10, name: "Industrial Heat Gun", category: "tools", subcategory: "Power Tools", description: "Variable temperature heat gun for industrial applications", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing"] },
    { id: 11, name: "Drill Bit Master Set", category: "tools", subcategory: "Accessories", description: "100-piece HSS cobalt drill bit set for metal and stone", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 12, name: "Heavy Duty Toolbox", category: "tools", subcategory: "Storage", description: "Steel rolling toolbox with 7 drawers and locking system", image: "https://images.unsplash.com/photo-1581244276891-998011506634?w=500&q=80", industries: ["automotive", "manufacturing"] },
    { id: 13, name: "Soldering Station Digital", category: "tools", subcategory: "Electrical", description: "ESD-safe digital soldering station for electronics repair", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy"] },
    { id: 14, name: "Industrial Staple Gun", category: "tools", subcategory: "Hand Tools", description: "Professional manual staple gun for upholstery and construction", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 15, name: "Torque Wrench Set", category: "tools", subcategory: "Measuring", description: "Click-type torque wrench set for precision automotive work", image: "https://images.unsplash.com/photo-1586864387789-628af9fea93f?w=500&q=80", industries: ["automotive"] },
    { id: 16, name: "Circular Saw 7.25-Inch", category: "tools", subcategory: "Power Tools", description: "High-torque circular saw for wood and composite cutting", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 17, name: "Metal File Set", category: "tools", subcategory: "Hand Tools", description: "10-piece industrial metal file set with ergonomic grips", image: "https://images.unsplash.com/photo-1581093196277-9f608adec699?w=500&q=80", industries: ["manufacturing"] },
    { id: 18, name: "Precision Screwdriver Set", category: "tools", subcategory: "Hand Tools", description: "25-piece toolkit for small electronics and instruments", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy"] },
    { id: 19, name: "Step Ladder 8ft", category: "tools", subcategory: "Hardware", description: "Fiberglass non-conductive step ladder for electrical work", image: "https://images.unsplash.com/photo-1508615070457-7baeba4003ab?w=500&q=80", industries: ["construction", "energy"] },
    { id: 20, name: "Bolt Extractor Set", category: "tools", subcategory: "Hand Tools", description: "Impact-grade bolt extractor set for damaged fasteners", image: "https://images.unsplash.com/photo-1586864387789-628af9fea93f?w=500&q=80", industries: ["automotive"] },
    { id: 21, name: "Wet/Dry Shop Vac", category: "tools", subcategory: "Cleaning", description: "12-gallon industrial vacuum for debris and liquid cleanup", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 22, name: "Hammer Drill 1/2-Inch", category: "tools", subcategory: "Power Tools", description: "High-power corded hammer drill for concrete and masonry", image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&q=80", industries: ["construction"] },
    { id: 23, name: "Leveling Rod 5m", category: "tools", subcategory: "Measuring", description: "Telescopic aluminum leveling rod for surveying", image: "https://images.unsplash.com/photo-1534398079543-7ae6d016b86a?w=500&q=80", industries: ["construction"] },
    { id: 24, name: "Wire Stripper/Crimper", category: "tools", subcategory: "Electrical", description: "Professional 9-in-1 wire stripping and crimping tool", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&q=80", industries: ["energy"] },
    { id: 25, name: "Heavy Duty C-Clamps", category: "tools", subcategory: "Hardware", description: "Industrial steel C-clamp set for welding and fabrication", image: "https://images.unsplash.com/photo-1581244276891-998011506634?w=500&q=80", industries: ["manufacturing"] },
    { id: 26, name: "Sheet Metal Snips", category: "tools", subcategory: "Hand Tools", description: "Aviation-style snips for straight and curved metal cutting", image: "https://images.unsplash.com/photo-1581093196277-9f608adec699?w=500&q=80", industries: ["manufacturing"] },
    { id: 27, name: "Utility Knife Bulk Pack", category: "tools", subcategory: "Hand Tools", description: "Retractable industrial utility knives with 100 spare blades", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 28, name: "Magnetic Parts Tray", category: "tools", subcategory: "Accessories", description: "Stainless steel magnetic tray for holding small fasteners", image: "https://images.unsplash.com/photo-1586864387789-628af9fea93f?w=500&q=80", industries: ["automotive"] },
    { id: 29, name: "Spirit Level Set", category: "tools", subcategory: "Measuring", description: "3-piece magnetic spirit level set (24, 48, 72-inch)", image: "https://images.unsplash.com/photo-1534398079543-7ae6d016b86a?w=500&q=80", industries: ["construction"] },
    { id: 30, name: "Air Compressor Portable", category: "tools", subcategory: "Air Tools", description: "6-gallon pancake air compressor for jobsite pneumatic tools", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["construction"] },

    // ELECTRICAL & ICT (30 Products)
    { id: 31, name: "Armored Power Cable", category: "electrical-ict", subcategory: "Power", description: "SWA armored cable for underground power distribution", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&q=80", industries: ["energy", "construction"] },
    { id: 32, name: "Main Distribution Board", category: "electrical-ict", subcategory: "Power", description: "Industrial 3-phase distribution board with MCCB protection", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing", "energy"] },
    { id: 33, name: "Managed Network Switch", category: "electrical-ict", subcategory: "ICT", description: "48-port Gigabit PoE+ managed switch for enterprise", image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=80", industries: ["education", "government"] },
    { id: 34, name: "10kVA Online UPS", category: "electrical-ict", subcategory: "Power", description: "Double-conversion online UPS for critical data centers", image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?w=500&q=80", industries: ["healthcare", "education"] },
    { id: 35, name: "IP Security Camera 4K", category: "electrical-ict", subcategory: "ICT", description: "Outdoor vandal-proof dome camera with night vision", image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=500&q=80", industries: ["government", "healthcare"] },
    { id: 36, name: "Solar Inverter 5kW", category: "electrical-ict", subcategory: "Solar", description: "High-efficiency grid-tied solar inverter with monitoring", image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=500&q=80", industries: ["energy", "agriculture"] },
    { id: 37, name: "Workstation PC Pro", category: "electrical-ict", subcategory: "ICT", description: "High-performance workstation with 64GB RAM and Xeon CPU", image: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=500&q=80", industries: ["education", "government"] },
    { id: 38, name: "Circuit Breaker 100A", category: "electrical-ict", subcategory: "Components", description: "Molded case circuit breaker (MCCB) for industrial use", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 39, name: "LED Panel 60x60", category: "electrical-ict", subcategory: "Lighting", description: "Ultra-slim LED ceiling panel for office lighting", image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=500&q=80", industries: ["healthcare", "education"] },
    { id: 40, name: "Fiber Optic Patch Panel", category: "electrical-ict", subcategory: "ICT", description: "24-port LC duplex fiber optic patch panel with cable management", image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=80", industries: ["education", "government"] },
    { id: 41, name: "Variable Frequency Drive", category: "electrical-ict", subcategory: "Power", description: "Industrial VFD motor controller for speed regulation", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing"] },
    { id: 42, name: "Automatic Transfer Switch", category: "electrical-ict", subcategory: "Power", description: "ATS for seamless switching between grid and generator", image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=500&q=80", industries: ["healthcare", "energy"] },
    { id: 43, name: "Wireless Access Point", category: "electrical-ict", subcategory: "ICT", description: "Enterprise-grade WiFi 6 access point dual-band", image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=80", industries: ["education", "government"] },
    { id: 44, name: "Electrical PVC Conduit", category: "electrical-ict", subcategory: "Installation", description: "25mm heavy-duty electrical PVC conduit (3m length)", image: "https://images.unsplash.com/photo-1621905251603-4f964af5d400?w=500&q=80", industries: ["construction", "energy"] },
    { id: 45, name: "Industrial LED High Bay", category: "electrical-ict", subcategory: "Lighting", description: "200W high bay LED light for warehouse application", image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 46, name: "Data Server Cabinet 42U", category: "electrical-ict", subcategory: "ICT", description: "Standard 19-inch server rack with cooling fans", image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?w=500&q=80", industries: ["education", "government"] },
    { id: 47, name: "Control Cable Multi-Core", category: "electrical-ict", subcategory: "Power", description: "Shielded multi-core control cable for industrial sensors", image: "https://images.unsplash.com/photo-1621905251603-4f964af5d400?w=500&q=80", industries: ["manufacturing"] },
    { id: 48, name: "Voltage Stabilizer 5kVA", category: "electrical-ict", subcategory: "Power", description: "Servo-controlled voltage stabilizer for electronic equipment", image: "https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=500&q=80", industries: ["healthcare", "energy"] },
    { id: 49, name: "Network Rackmount UPS", category: "electrical-ict", subcategory: "ICT", description: "2U rackmount UPS with network management card", image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc51?w=500&q=80", industries: ["education", "government"] },
    { id: 50, name: "Wall-Mount Data Rack 6U", category: "electrical-ict", subcategory: "ICT", description: "Compact wall-mount network enclosure with glass door", image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=80", industries: ["education", "healthcare"] },
    { id: 51, name: "CAT6 Network Cable Roll", category: "electrical-ict", subcategory: "ICT", description: "305m box of pure copper CAT6 UTP network cable", image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&q=80", industries: ["education", "government"] },
    { id: 52, name: "Smart IP Phone", category: "electrical-ict", subcategory: "ICT", description: "Business VoIP phone with color display and HD audio", image: "https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=500&q=80", industries: ["education", "government"] },
    { id: 53, name: "Street Light LED 150W", category: "electrical-ict", subcategory: "Lighting", description: "IP66 outdoor LED street light with aluminum housing", image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=500&q=80", industries: ["government", "construction"] },
    { id: 54, name: "Flexible Electrical Wire", category: "electrical-ict", subcategory: "Installation", description: "Roll of 2.5mm flexible copper wire (all colors)", image: "https://images.unsplash.com/photo-1621905251603-4f964af5d400?w=500&q=80", industries: ["energy", "construction"] },
    { id: 55, name: "Industrial Socket & Plug", category: "electrical-ict", subcategory: "Installation", description: "Heavy-duty 32A 3-phase industrial power connectors", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 56, name: "Earth Rod Copper", category: "electrical-ict", subcategory: "Grounding", description: "Solid copper earth rod for electrical system grounding", image: "https://images.unsplash.com/photo-1621905251603-4f964af5d400?w=500&q=80", industries: ["energy", "construction"] },
    { id: 57, name: "Heat Shrink Tubing Kit", category: "electrical-ict", subcategory: "Installation", description: "Assorted sizes of fire-retardant heat shrink tubes", image: "https://images.unsplash.com/photo-1621905251603-4f964af5d400?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 58, name: "Contactors & Overloads", category: "electrical-ict", subcategory: "Control", description: "Magnetic contactors for industrial motor starters", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing"] },
    { id: 59, name: "Digital Timer Switch", category: "electrical-ict", subcategory: "Control", description: "Programmable digital timer for automated electrical systems", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 60, name: "Isolator Switch 63A", category: "electrical-ict", subcategory: "Power", description: "Weatherproof industrial isolator switch IP66", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["energy", "construction"] },

    // BUILDING MATERIALS (30 Products)
    { id: 61, name: "Portland Cement 50kg", category: "building-materials", subcategory: "Cement", description: "Grade 42.5N general purpose Portland cement", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 62, name: "Steel Reinforcement 12mm", category: "building-materials", subcategory: "Steel", description: "High tensile deformed rebar for concrete reinforcement", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=500&q=80", industries: ["construction"] },
    { id: 63, name: "Corrugated Roof Sheets", category: "building-materials", subcategory: "Roofing", description: "Zinc-aluminum coated corrugated roofing sheets", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 64, name: "PPR Internal Pipe", category: "building-materials", subcategory: "Plumbing", description: "20mm PPR pipe for hot and cold water plumbing", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 65, name: "Premium Emulsion Paint", category: "building-materials", subcategory: "Finishing", description: "Silk finish interior emulsion paint (20L bucket)", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&q=80", industries: ["construction", "hospitality"] },
    { id: 66, name: "Concrete Blocks 6-inch", category: "building-materials", subcategory: "Masonry", description: "Standard load-bearing hollow concrete blocks", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 67, name: "Clay Bricks (Face Bricks)", category: "building-materials", subcategory: "Masonry", description: "High-quality red clay bricks for decorative walling", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=500&q=80", industries: ["construction"] },
    { id: 68, name: "Ceramic Floor Tiles", category: "building-materials", subcategory: "Finishing", description: "60x60cm high-gloss ceramic tiles for commercial flooring", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction", "hospitality"] },
    { id: 69, name: "PVC Drain Pipe 110mm", category: "building-materials", subcategory: "Plumbing", description: "Standard underground drainage PVC pipe", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 70, name: "Gypsum Board 9mm", category: "building-materials", subcategory: "Masonry", description: "Standard gypsum wallboard for ceilings and partitions", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&q=80", industries: ["construction"] },
    { id: 71, name: "Timber Joists 4x2", category: "building-materials", subcategory: "Timber", description: "Treated structural timber for roofing and framing", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 72, name: "Aluminum Window Frames", category: "building-materials", subcategory: "Fixtures", description: "Powder-coated aluminum sliding window sections", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 73, name: "Tile Adhesive 20kg", category: "building-materials", subcategory: "Finishing", description: "Heavy-duty tile cement for vertical and horizontal tiles", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&q=80", industries: ["construction"] },
    { id: 74, name: "Water Tank 1000L", category: "building-materials", subcategory: "Storage", description: "Polyethylene vertical water storage tank", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&q=80", industries: ["construction", "agriculture"] },
    { id: 75, name: "Steel Mesh Sheet", category: "building-materials", subcategory: "Steel", description: "Welded steel mesh for driveway reinforcement", image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=500&q=80", industries: ["construction"] },
    { id: 76, name: "External Gloss Paint", category: "building-materials", subcategory: "Finishing", description: "Weather-resistant gloss paint for outdoor metal/wood", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&q=80", industries: ["construction"] },
    { id: 77, name: "Brass Ball Valve 1-Inch", category: "building-materials", subcategory: "Plumbing", description: "Full-port brass ball valve for water control", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 78, name: "Fiber Glass Insulation", category: "building-materials", subcategory: "Masonry", description: "Thermal and acoustic fiberglass insulation roll", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 79, name: "Heavy Duty Door Frame", category: "building-materials", subcategory: "Fixtures", description: "Pre-formed steel door frame for security doors", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 80, name: "Window Glass Sheet", category: "building-materials", subcategory: "Fixtures", description: "4mm clear float glass for building windows", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 81, name: "Bitumen Sealant", category: "building-materials", subcategory: "Roofing", description: "Waterproofing bitumen sealant for roof joints", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 82, name: "Galvanized Nails 3-inch", category: "building-materials", subcategory: "Hardware", description: "Bulk box (50kg) of galvanized wire nails", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 83, name: "Expansion Joint Filler", category: "building-materials", subcategory: "Cement", description: "Pre-molded joint filler for concrete slabs", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 84, name: "Aggregate stone (Grade 1)", category: "building-materials", subcategory: "Cement", description: "Crushed aggregate for high-strength concrete", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 85, name: "Building Sand (Tone)", category: "building-materials", subcategory: "Cement", description: "Washed river sand for plastering and mortar", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 86, name: "Manhole Cover Cast Iron", category: "building-materials", subcategory: "Masonry", description: "Heavy-duty cast iron manhole cover for roads", image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&q=80", industries: ["construction"] },
    { id: 87, name: "Plywood Marine Grade", category: "building-materials", subcategory: "Timber", description: "18mm marine plywood for moisture resistance", image: "https://images.unsplash.com/photo-1513467535987-fd81bc7d62f8?w=500&q=80", industries: ["construction"] },
    { id: 88, name: "Concrete Vibrator Rod", category: "building-materials", subcategory: "Accessories", description: "Flexible shaft for concrete vibrating machine", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 89, name: "Scaffolding Connector", category: "building-materials", subcategory: "Accessories", description: "Standard drop-forged scaffolding coupler", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },
    { id: 90, name: "Screws Bulk Master Pack", category: "building-materials", subcategory: "Hardware", description: "Assorted tech screws for metal and wood", image: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500&q=80", industries: ["construction"] },

    // INDUSTRIAL EQUIPMENT (30 Products)
    { id: 91, name: "Industrial Air Compressor", category: "industrial-equipment", subcategory: "Compressors", description: "10HP reciprocal air compressor with 500L tank", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "automotive"] },
    { id: 92, name: "Semi-Auto Forklift", category: "industrial-equipment", subcategory: "Material Handling", description: "2-ton battery-operated pallet stacker", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing", "other"] },
    { id: 93, name: "Diesel Engine 15HP", category: "industrial-equipment", subcategory: "Engines", description: "Single-cylinder diesel engine for pumps and mills", image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500&q=80", industries: ["agriculture", "manufacturing"] },
    { id: 94, name: "High Pressure Washer", category: "industrial-equipment", subcategory: "Cleaning", description: "Diesel-powered high pressure washer (3000 PSI)", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["automotive", "hospitality"] },
    { id: 95, name: "Centrifugal Pump 3-inch", category: "industrial-equipment", subcategory: "Pumps", description: "High-volume water pump for industrial irrigation", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["agriculture", "manufacturing"] },
    { id: 96, name: "Industrial Lathe Machine", category: "industrial-equipment", subcategory: "Machining", description: "High-precision manual gap-bed lathe machine", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing"] },
    { id: 97, name: "Welding Inverter 300A", category: "industrial-equipment", subcategory: "Welding", description: "Professional IGBT inverter stick welding machine", image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 98, name: "Electric Motor 3-Phase", category: "industrial-equipment", subcategory: "Engines", description: "5.5kW high-efficiency electric induction motor", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing", "energy"] },
    { id: 99, name: "Steel Belt Conveyor", category: "industrial-equipment", subcategory: "Material Handling", description: "10-meter modular belt conveyor for assembly lines", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing"] },
    { id: 100, name: "Industrial Drying Oven", category: "industrial-equipment", subcategory: "Thermal", description: "Large-capacity drying oven for industrial parts", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing"] },
    { id: 101, name: "Hydraulic Press 50T", category: "industrial-equipment", subcategory: "Machining", description: "Heavy-duty hydraulic shop press for industrial use", image: "https://images.unsplash.com/photo-1586864387789-628af9fea93f?w=500&q=80", industries: ["manufacturing", "automotive"] },
    { id: 102, name: "Vacuum Pump System", category: "industrial-equipment", subcategory: "Pumps", description: "Rotary vane vacuum pump for labs and industrial use", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "other"] },
    { id: 103, name: "Gearboxes & Speed Reducers", category: "industrial-equipment", subcategory: "Components", description: "Worm gear reduction units for conveyor drives", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing"] },
    { id: 104, name: "Platform Scale 1000kg", category: "industrial-equipment", subcategory: "Measuring", description: "Digital platform scale with stainless steel top", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "other"] },
    { id: 105, name: "Chain Block 3 Ton", category: "industrial-equipment", subcategory: "Lifting", description: "High-strength manual chain hoist lifter", image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 106, name: "Pneumatic Cylinder Module", category: "industrial-equipment", subcategory: "Components", description: "Double-acting air cylinder for automation", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing"] },
    { id: 107, name: "Steam Generator Unit", category: "industrial-equipment", subcategory: "Thermal", description: "Compact electric steam generator for industrial processes", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "hospitality"] },
    { id: 108, name: "Heat Exchanger Plate", category: "industrial-equipment", subcategory: "Thermal", description: "Stainless steel plate heat exchanger for cooling", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "energy"] },
    { id: 109, name: "Vibratory Feeder System", category: "industrial-equipment", subcategory: "Material Handling", description: "Automatic feeder for small components assembly", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing"] },
    { id: 110, name: "Industrial Fan Blower", category: "industrial-equipment", subcategory: "Cooling", description: "Heavy-duty centrifugal blower for ventilation", image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 111, name: "Plasma Cutter Pro", category: "industrial-equipment", subcategory: "Welding", description: "Inverter plasma cutting machine (60A) for clean cuts", image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 112, name: "Platform Hand Truck", category: "industrial-equipment", subcategory: "Material Handling", description: "Folding steel heavy-duty hand trolley (300kg)", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["other", "manufacturing"] },
    { id: 113, name: "Chemical Dosing Pump", category: "industrial-equipment", subcategory: "Pumps", description: "Precision diaphragm pump for chemical treatment", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "healthcare"] },
    { id: 114, name: "Pneumatic Valve 5-way", category: "industrial-equipment", subcategory: "Components", description: "Solenoid-operated pneumatic directional control valve", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["manufacturing"] },
    { id: 115, name: "Lubricating Grease Pump", category: "industrial-equipment", subcategory: "Lubrication", description: "Manual high-pressure grease dispenser system", image: "https://images.unsplash.com/photo-1581093196277-9f608adec699?w=500&q=80", industries: ["manufacturing", "automotive"] },
    { id: 116, name: "Air Handling Unit (Small)", category: "industrial-equipment", subcategory: "Cooling", description: "Modular AHU for commercial ventilation systems", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["hospitality", "healthcare"] },
    { id: 117, name: "Storage Tank Liner", category: "industrial-equipment", subcategory: "Thermal", description: "Protective epoxy liner for industrial liquid tanks", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing"] },
    { id: 118, name: "Vertical Milling Machine", category: "industrial-equipment", subcategory: "Machining", description: "Universal vertical milling machine with DRO", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing"] },
    { id: 119, name: "Cooling Tower Fan", category: "industrial-equipment", subcategory: "Cooling", description: "Variable pitch axial fan for industrial cooling towers", image: "https://images.unsplash.com/photo-1581094288338-2314dddb7ecc?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 120, name: "Automatic Strapping Machine", category: "industrial-equipment", subcategory: "Machining", description: "Box strapping and bundling machine for logistics", image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=500&q=80", industries: ["manufacturing", "other"] },

    // SAFETY EQUIPMENT (30 Products)
    { id: 121, name: "Safety Helmet Hard Hat", category: "safety-equipment", subcategory: "Head Protection", description: "Vented safety helmet with adjustable suspension", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 122, name: "Nitrile Safety Gloves", category: "safety-equipment", subcategory: "Hand Protection", description: "Cut-resistant nitrile coated work gloves (12 pack)", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 123, name: "Steel Toe Boot Pro", category: "safety-equipment", subcategory: "Foot Protection", description: "S3 grade puncture-resistant safety boots", image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 124, name: "High Vis Safety Vest", category: "safety-equipment", subcategory: "Visibility", description: "Standard reflective safety vest class 2", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "other"] },
    { id: 125, name: "Fire Extinguisher ABC 6kg", category: "safety-equipment", subcategory: "Fire Safety", description: "Multi-purpose dry powder fire extinguisher", image: "https://images.unsplash.com/photo-1611645179318-564d6fdeaee8?w=500&q=80", industries: ["hospitality", "government"] },
    { id: 126, name: "Full Body Fall Harness", category: "safety-equipment", subcategory: "Height Safety", description: "Universal size adjustable safety harness for roofs", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "energy"] },
    { id: 127, name: "Noise Cancelling Ear Muffs", category: "safety-equipment", subcategory: "Hearing Protection", description: "Over-the-head ear muffs with 30dB NRR", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 128, name: "Anti-Fog Safety Goggles", category: "safety-equipment", subcategory: "Eye Protection", description: "Wide-vision goggles with anti-fog coating", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["manufacturing", "healthcare"] },
    { id: 129, name: "N95 Particulate Respirator", category: "safety-equipment", subcategory: "Respiratory", description: "Valved mask for dust and mist protection (Box 20)", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["healthcare", "construction"] },
    { id: 130, name: "First Aid Kit Industrial XL", category: "safety-equipment", subcategory: "Medical", description: "Wall-mounted comprehensive 100-person first aid kit", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["government", "education"] },
    { id: 131, name: "Eye Wash Station Portable", category: "safety-equipment", subcategory: "Medical", description: "Self-contained Gravity-fed emergency eye wash unit", image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&q=80", industries: ["manufacturing", "healthcare"] },
    { id: 132, name: "Chemical Spill Kit 50L", category: "safety-equipment", subcategory: "Spill Containment", description: "Universal spill kit for industrial oil and chemicals", image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500&q=80", industries: ["manufacturing", "energy"] },
    { id: 133, name: "Safety Signage Set Master", category: "safety-equipment", subcategory: "Signage", description: "Common site signs (Entry, PPE required, Danger)", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "manufacturing"] },
    { id: 134, name: "Lockout Tagout Kit Pro", category: "safety-equipment", subcategory: "Electrical Safety", description: "Electrical isolation kit with padlocks and tags", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 135, name: "Flame Retardant Overall", category: "safety-equipment", subcategory: "Body Protection", description: "100% cotton flame retardant work suit (Orange)", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 136, name: "Safety Barrier Tape 500m", category: "safety-equipment", subcategory: "Visibility", description: "Yellow/Black hazard warning barrier tape", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "government"] },
    { id: 137, name: "Welding Face Shield", category: "safety-equipment", subcategory: "Eye Protection", description: "Auto-darkening welding helmet with shade adjust", image: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=500&q=80", industries: ["manufacturing", "construction"] },
    { id: 138, name: "Safety Cone 28-inch", category: "safety-equipment", subcategory: "Visibility", description: "PVC traffic cone with reflective collars", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["government", "construction"] },
    { id: 139, name: "Acid-Resistant Apron", category: "safety-equipment", subcategory: "Body Protection", description: "PVC/Nitrile heavy-duty chemical resistant apron", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["manufacturing", "healthcare"] },
    { id: 140, name: "Shock Absorbing Lanyard", category: "safety-equipment", subcategory: "Height Safety", description: "Twin tail lanyard with large scaffold hooks", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction", "energy"] },
    { id: 141, name: "Gas Detector 4-Gas Pro", category: "safety-equipment", subcategory: "Detection", description: "Portable multi-gas detector (O2, LEL, CO, H2S)", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy", "manufacturing"] },
    { id: 142, name: "Insulated Rubber Matting", category: "safety-equipment", subcategory: "Electrical Safety", description: "Class 0 industrial VDE insulated safety floor mat", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["energy"] },
    { id: 143, name: "High Vis Waterproof Jacket", category: "safety-equipment", subcategory: "Visibility", description: "Breathable fluorescent yellow winter work jacket", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["other", "construction"] },
    { id: 144, name: "Knee Protection Pads", category: "safety-equipment", subcategory: "Body Protection", description: "Gel-padded heavy-duty protective knee pads", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["construction"] },
    { id: 145, name: "Fire Blanket Large", category: "safety-equipment", subcategory: "Fire Safety", description: "1.2m x 1.8m fire blanket for industrial kitchens", image: "https://images.unsplash.com/photo-1611645179318-564d6fdeaee8?w=500&q=80", industries: ["hospitality", "manufacturing"] },
    { id: 146, name: "Industrial Arc Flash Suit", category: "safety-equipment", subcategory: "Electrical Safety", description: "40 cal/cm2 complete arc flash protection kit", image: "https://images.unsplash.com/photo-1621905252472-83d5244bb20c?w=500&q=80", industries: ["energy"] },
    { id: 147, name: "Disposable Coveralls Pro", category: "safety-equipment", subcategory: "Body Protection", description: "Microporous Type 5/6 disposable protection suit (Pack 25)", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["manufacturing", "healthcare"] },
    { id: 148, name: "Life Jacket Automatic", category: "safety-equipment", subcategory: "Water Safety", description: "Inflatable high-buoyancy life jacket for marine work", image: "https://images.unsplash.com/photo-1603712725038-45748c4b87e9?w=500&q=80", industries: ["other"] },
    { id: 149, name: "Anti-Static Lab Coat", category: "safety-equipment", subcategory: "Body Protection", description: "ESD-safe lab coat for electronic cleanrooms", image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&q=80", industries: ["energy", "healthcare"] },
    { id: 150, name: "Intrinsically Safe Torch", category: "safety-equipment", subcategory: "Detection", description: "ATEX explosion-proof high-power LED flashlight", image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80", industries: ["energy", "manufacturing"] }
];

// Helper to filter products
function filterProducts(filters) {
    let filtered = [...productsDB];

    if (filters.category && filters.category !== 'all') {
        filtered = filtered.filter(p => p.category.toLowerCase() === filters.category.toLowerCase());
    }

    if (filters.search) {
        const query = filters.search.toLowerCase();
        filtered = filtered.filter(p =>
            p.name.toLowerCase().includes(query) ||
            p.description.toLowerCase().includes(query) ||
            p.subcategory.toLowerCase().includes(query)
        );
    }

    if (filters.sort) {
        switch (filters.sort) {
            case 'name-asc':
                filtered.sort((a, b) => a.name.localeCompare(b.name));
                break;
            case 'name-desc':
                filtered.sort((a, b) => b.name.localeCompare(a.name));
                break;
        }
    }

    return filtered;
}

// Helper to get unique categories (if needed dynamically)
function getCategories() {
    return [...new Set(productsDB.map(p => p.category))];
}

// Export for window use
if (typeof window !== 'undefined') {
    window.ProductsDB = {
        products: productsDB,
        filterProducts,
        getCategories
    };
}
